repos:
  - repo: local
    hooks:
    - id: oactool validate
      name: oactool validate
      entry: poetry run oactool validate
      language: system
      files: ^completions/.+\.json$
  - repo: local
    hooks:
    - id: poetry
      name: poetry check
      entry: poetry check
      pass_filenames: false
      language: system
      files: ^pyproject\.toml$
