repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: poetry run black .
      language: system
      pass_filenames: false
  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: poetry run isort -y
      language: system
      pass_filenames: false
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: poetry run flake8 .
      language: system
      pass_filenames: false
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: poetry run oactool
      pass_filenames: false
      language: system
      types: [python]
  - repo: local
    hooks:
    - id: poetry
      name: poetry check
      entry: poetry check
      pass_filenames: false
      language: system
      files: ^pyproject\.toml$
